-- Create the Players table
CREATE TABLE IF NOT EXISTS Players (
    ID INTEGER PRIMARY KEY,
    Name TEXT,
    Nationality TEXT,
    Age INTEGER,
    Position TEXT,
    CurrentClub TEXT,
    UNIQUE (Name, Nationality, Age, Position, CurrentClub)
);

-- Insert players
INSERT OR IGNORE INTO Players (Name, Nationality, Age, Position, CurrentClub)
VALUES 
    -- Los Pollos Hermanos
    ('Walter White', 'United States', 52, 'Goalkeeper', 'Los Pollos Hermanos'),
    ('Jesse Pinkman', 'United States', 35, 'Central Defender', 'Los Pollos Hermanos'),
    ('Skyler White', 'United States', 48, 'Left Back', 'Los Pollos Hermanos'),
    ('Hank Schrader', 'United States', 47, 'Right Back', 'Los Pollos Hermanos'),
    ('Mike Ehrmantraut', 'Germany', 57, 'Central Midfielder', 'Los Pollos Hermanos'),
    ('Saul Goodman', 'United States', 48, 'Attacking Midfielder', 'Los Pollos Hermanos'),
    ('Gus Fring', 'Chile', 54, 'Right Winger', 'Los Pollos Hermanos'),
    ('Todd Alquist', 'United States', 28, 'Striker', 'Los Pollos Hermanos'),
    ('Lydia Rodarte-Quayle', 'United States', 39, 'Left Winger', 'Los Pollos Hermanos'),
    ('Steven Gomez', 'United States', 41, 'Central Defender', 'Los Pollos Hermanos'),
    ('Badger Mayhew', 'United States', 35, 'Attacking Midfielder', 'Los Pollos Hermanos'),
    ('Skinny Pete', 'United States', 37, 'Right Winger', 'Los Pollos Hermanos'),
    ('Gretchen Schwartz', 'United States', 52, 'Central Midfielder', 'Los Pollos Hermanos'),
    ('Elliot Schwartz', 'United States', 53, 'Defensive Midfielder', 'Los Pollos Hermanos'),
    ('Tuco Salamanca', 'Mexico', 35, 'Striker', 'Los Pollos Hermanos'),
    ('Hector Salamanca', 'Mexico', 76, 'Central Defender', 'Los Pollos Hermanos'),
    ('Gale Boetticher', 'United States', 40, 'Attacking Midfielder', 'Los Pollos Hermanos'),
    ('Huell Babineaux', 'United States', 42, 'Defensive Midfielder', 'Los Pollos Hermanos'),
    ('Lawson', 'United States', 45, 'Left Back', 'Los Pollos Hermanos'),

    -- Benfica
    ('Anatoliy Trubin', 'Ukraine', 22, 'Goalkeeper', 'Benfica'),
    ('Samuel Soares', 'Portugal', 21, 'Goalkeeper', 'Benfica'),
    ('Leo Kokubo', 'Japan', 22, 'Goalkeeper', 'Benfica'),
    ('António Silva', 'Portugal', 20, 'Central Defender', 'Benfica'),
    ('Morato', 'Brazil', 22, 'Central Defender', 'Benfica'),
    ('Tomás Araújo', 'Portugal', 21, 'Central Defender', 'Benfica'),
    ('Nicolás Otamendi', 'Argentina', 35, 'Central Defender', 'Benfica'),
    ('David Jurásek', 'Czech Republic', 23, 'Left Back', 'Benfica'),
    ('Juan Bernat', 'Spain', 30, 'Left Back', 'Benfica'),
    ('Alexander Bah', 'Denmark', 26, 'Right Back', 'Benfica'),
    ('João Neves', 'Portugal', 19, 'Defensive Midfielder', 'Benfica'),
    ('Florentino', 'Portugal', 24, 'Defensive Midfielder', 'Benfica'),
    ('Orkun Kökçü', 'Turkey', 23, 'Central Midfielder', 'Benfica'),
    ('Gonçalo Guedes', 'Portugal', 27, 'Left Winger', 'Benfica'),
    ('David Neres', 'Brazil', 26, 'Right Winger', 'Benfica'),
    ('Ángel Di María', 'Argentina', 35, 'Right Winger', 'Benfica'),
    ('Tiago Gouveia', 'Portugal', 22, 'Right Winger', 'Benfica'),
    ('Rafa', 'Portugal', 30, 'Second Striker', 'Benfica'),
    ('Marcos Leonardo', 'Brazil', 20, 'Striker', 'Benfica'),
    ('Arthur Cabral', 'Brazil', 25, 'Striker', 'Benfica'),
    ('Petar Musa', 'Croatia', 25, 'Striker', 'Benfica'),
    ('Casper Tengstedt', 'Denmark', 23, 'Striker', 'Benfica'),

    -- Sporting
    ('Franco Israel', 'Uruguay', 23, 'Goalkeeper', 'Sporting'),
    ('Diego Callai', 'Brazil', 19, 'Goalkeeper', 'Sporting'),
    ('Antonio Adán', 'Spain', 36, 'Goalkeeper', 'Sporting'),
    ('Gonçalo Inácio', 'Portugal', 22, 'Central Defender', 'Sporting'),
    ('Ousmane Diomande', 'Ivory Coast', 20, 'Central Defender', 'Sporting'),
    ('Jerry St. Juste', 'Netherlands', 27, 'Central Defender', 'Sporting'),
    ('Sebastián Coates', 'Uruguay', 33, 'Central Defender', 'Sporting'),
    ('Eduardo Quaresma', 'Portugal', 21, 'Central Defender', 'Sporting'),
    ('João Muniz', 'Portugal', 18, 'Central Defender', 'Sporting'),
    ('Rafael', 'Brazil', 20, 'Central Defender', 'Sporting'),
    ('Nuno Santos', 'Portugal', 28, 'Left Back', 'Sporting'),
    ('Matheus Reis', 'Brazil', 28, 'Left Back', 'Sporting'),
    ('Iván Fresneda', 'Spain', 19, 'Right Back', 'Sporting'),
    ('Ricardo Esgaio', 'Portugal', 30, 'Right Back', 'Sporting'),
    ('Morten Hjulmand', 'Denmark', 24, 'Defensive Midfielder', 'Sporting'),
    ('Dário Essugo', 'Portugal', 18, 'Defensive Midfielder', 'Sporting'),
    ('Hidemasa Morita', 'Japan', 28, 'Central Midfielder', 'Sporting'),
    ('Daniel Bragança', 'Portugal', 24, 'Central Midfielder', 'Sporting'),
    ('Trincão', 'Portugal', 24, 'Left Winger', 'Sporting'),
    ('Pedro Gonçalves', 'Portugal', 25, 'Right Winger', 'Sporting'),
    ('Marcus Edwards', 'England', 25, 'Right Winger', 'Sporting'),
    ('Geny Catamo', 'Mozambique', 22, 'Right Winger', 'Sporting'),
    ('Rafael Camacho', 'Portugal', 23, 'Right Winger', 'Sporting'),
    ('Viktor Gyökeres', 'Sweden', 25, 'Striker', 'Sporting'),
    ('Paulinho', 'Portugal', 31, 'Striker', 'Sporting'),
    ('Rodrigo Ribeiro', 'Portugal', 18, 'Striker', 'Sporting'),

    -- Porto
    ('Diogo Costa', 'Portugal', 24, 'Goalkeeper', 'Porto'),
    ('Cláudio Ramos', 'Portugal', 32, 'Goalkeeper', 'Porto'),
    ('Samuel Portugal', 'Brazil', 29, 'Goalkeeper', 'Porto'),
    ('David Carmo', 'Portugal', 24, 'Central Defender', 'Porto'),
    ('Fábio Cardoso', 'Portugal', 29, 'Central Defender', 'Porto'),
    ('Zé Pedro', 'Portugal', 26, 'Central Defender', 'Porto'),
    ('Pepe', 'Portugal', 40, 'Central Defender', 'Porto'),
    ('Iván Marcano', 'Spain', 36, 'Central Defender', 'Porto'),
    ('Wendell', 'Brazil', 30, 'Left Back', 'Porto'),
    ('Zaidu', 'Nigeria', 26, 'Left Back', 'Porto'),
    ('João Mário', 'Portugal', 24, 'Right Back', 'Porto'),
    ('Jorge Sánchez', 'Mexico', 26, 'Right Back', 'Porto'),
    ('Alan Varela', 'Argentina', 22, 'Defensive Midfielder', 'Porto'),
    ('Marko Grujić', 'Serbia', 27, 'Defensive Midfielder', 'Porto'),
    ('Stephen Eustaquio', 'Canada', 27, 'Central Midfielder', 'Porto'),
    ('Nico González', 'Spain', 22, 'Central Midfielder', 'Porto'),
    ('Romário Baró', 'Portugal', 23, 'Central Midfielder', 'Porto'),
    ('Iván Jaime', 'Spain', 23, 'Attacking Midfielder', 'Porto'),
    ('André Franco', 'Portugal', 25, 'Attacking Midfielder', 'Porto'),
    ('Pepê', 'Brazil', 26, 'Left Winger', 'Porto'),
    ('Galeno', 'Brazil', 26, 'Left Winger', 'Porto'),
    ('Francisco Conceição', 'Portugal', 21, 'Right Winger', 'Porto'),
    ('Gonçalo Borges', 'Portugal', 22, 'Right Winger', 'Porto'),
    ('Evanilson', 'Brazil', 24, 'Striker', 'Porto'),
    ('Mehdi Taremi', 'Iran', 31, 'Striker', 'Porto'),
    ('Toni Martínez', 'Spain', 26, 'Striker', 'Porto'),
    ('Danny Namaso', 'England', 23, 'Striker', 'Porto');
